name: deepseek-r1 intel-npu

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      snap-channel:
        description: 'Snap store channel to test'
        required: true
        type: string

jobs:
  test-chat:
    uses: ./.github/workflows/test-chat.yml
    with:
      snap-name: deepseek-r1
      snap-channel: ${{ inputs.snap-channel }}
      job-queue: hp-prodesk-4-sff-g1i-desktop-ai-pc-ag8j7av-c36704
      # job-queue: hp-zbook-fury-g1i-18-inch-mobile-workstation-pc-1234567aba-c36712 # alternative
      provision-data: "url: https://tel-image-cache.canonical.com/oem-share/sutton/releases/noble/oem-24.04c/20251009-80/sutton-noble-oem-24.04c-20251009-80.iso"
      expected-engine: ""
      select-engine: "intel-npu"
      expected-tps: 0
      install-nvidia-driver-version: ""
      install-intel-npu-driver: true
