name: deepseek-r1 intel-cpu

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      snap-channel:
        description: 'Snap store channel to test'
        required: true
        type: string

jobs:
  test-chat:
    uses: ./.github/workflows/test-chat.yml
    secrets: inherit
    with:
      snap-name: deepseek-r1
      snap-channel: ${{ inputs.snap-channel }}
      job-queue: mir-intel-noble
      provision-data: "distro: noble"
      expected-engine: ""
      select-engine: "intel-cpu"
      expected-tps: 0
      install-nvidia-driver-version: ""
