name: deepseek-r1 cpu

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      snap-channel:
        description: 'Snap store channel to test'
        required: true
        type: string

jobs:
  test-chat:
    uses: ./.github/workflows/test-chat.yml
    with:
      snap-name: deepseek-r1
      snap-channel: ${{ inputs.snap-channel }}
      job-queue: maas-systemtests-amd64
      provision-data: "distro: noble"
      expected-engine: ""
      select-engine: "cpu"
      expected-tps: 0
      install-nvidia-driver-version: ""
