name: gemma3

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      snap-channel:
        description: 'Snap store channel to test'
        required: true
        type: string

jobs:
  test-vlm:
    name: gemma3 ${{ matrix.jobs.select-engine }}
    strategy:
      fail-fast: false
      matrix:
        jobs:
          - select-engine: cpu
            job-queue: maas-systemtests-amd64
            provision-data: "distro: noble"

          - select-engine: intel-cpu
            job-queue: mir-intel-noble
            provision-data: "distro: noble"

          - select-engine: intel-gpu
            job-queue: 202111-29603 # Alder Lake, GPU 8086:4680
            provision-data: "distro: noble"

          - select-engine: nvidia-gpu-amd64
            job-queue: anbox-nvidia-amd64
            provision-data: "distro: noble"
            expected-tps: 10
            install-nvidia-driver-version: 550
          
          - select-engine: amd-gpu-amd64
            job-queue: 202203-30094 # Core-i7-12850HX + Radeon PRO W6600M
            provision-data: "distro: noble"

          # Skip nvidia-gpu-arm64 engine as we do not have a test machine for it

    uses: ./.github/workflows/test-vlm.yaml
    secrets: inherit
    with:
      snap-name: gemma3
      snap-channel: ${{ inputs.snap-channel }}
      job-queue: ${{ matrix.jobs.job-queue }}
      provision-data: ${{ matrix.jobs.provision-data }}
      select-engine: ${{ matrix.jobs.select-engine }}
      install-nvidia-driver-version: ${{ matrix.jobs.install-nvidia-driver-version }}
      install-intel-npu-driver: ${{ matrix.jobs.install-intel-npu-driver == true }}


  test-chat:
    name: gemma3 ${{ matrix.jobs.select-engine }}
    strategy:
      fail-fast: false
      matrix:
        jobs:
          # cpu-xsmall engine does not support image input
          - select-engine: cpu-xsmall
            job-queue: maas-systemtests-amd64
            provision-data: "distro: noble"

    uses: ./.github/workflows/test-chat.yaml
    secrets: inherit
    with:
      snap-name: gemma3
      snap-channel: ${{ inputs.snap-channel }}
      job-queue: ${{ matrix.jobs.job-queue }}
      provision-data: ${{ matrix.jobs.provision-data }}
      select-engine: ${{ matrix.jobs.select-engine }}
      install-nvidia-driver-version: ${{ matrix.jobs.install-nvidia-driver-version }}
      install-intel-npu-driver: ${{ matrix.jobs.install-intel-npu-driver == true }}