name: nemotron-3-nano all

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      snap-channel:
        description: 'Snap store channel to test'
        required: true
        type: string

jobs:
  test-chat:
    name: nemotron-3-nano ${{ matrix.jobs.select-engine }}
    strategy:
      fail-fast: false
      matrix:
        jobs:
          - select-engine: cpu
            job-queue: maas-systemtests-amd64
            provision-data: "distro: noble"

          - select-engine: nvidia-gpu
            job-queue: anbox-nvidia-amd64
            provision-data: "distro: noble"
            expected-tps: 10
            install-nvidia-driver-version: 550

    uses: ./.github/workflows/test-chat.yaml
    secrets: inherit
    with:
      snap-name: nemotron-3-nano
      snap-channel: ${{ inputs.snap-channel }}
      job-queue: ${{ matrix.jobs.job-queue }}
      provision-data: ${{ matrix.jobs.provision-data }}
      select-engine: ${{ matrix.jobs.select-engine }}
      install-nvidia-driver-version: ${{ matrix.jobs.install-nvidia-driver-version }}
      install-intel-npu-driver: ${{ matrix.jobs.install-intel-npu-driver == true }}
