name: qwen-vl

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      snap-channel:
        description: 'Snap store channel to test'
        required: true
        type: string

jobs:
  test-chat:
    name: qwen-vl ${{ matrix.jobs.select-engine }}
    strategy:
      fail-fast: false
      matrix:
        jobs:
          - select-engine: cpu
            job-queue: maas-systemtests-amd64
            provision-data: "distro: noble"

          - select-engine: cpu-avx512
            job-queue: maas-systemtests-amd64
            provision-data: "distro: noble"

          - select-engine: cpu-tiny
            job-queue: maas-systemtests-amd64
            provision-data: "distro: noble"

          - select-engine: intel-cpu
            job-queue: mir-intel-noble
            provision-data: "distro: noble"

          - select-engine: intel-gpu
            job-queue: 202111-29603 # Alder Lake, GPU 8086:4680
            provision-data: "distro: noble"

          # Skip intel-npu engine as it requires an image input
          # See https://github.com/canonical/inference-snaps/issues/96

          - select-engine: cuda
            job-queue: anbox-nvidia-amd64
            provision-data: "distro: noble"
            expected-tps: 10
            install-nvidia-driver-version: 550

          - select-engine: ampere-altra
            job-queue: ampere-altra
            provision-data: "distro: noble"
            expected-tps: 9

          - select-engine: ampere-one
            job-queue: ampere-one
            provision-data: "distro: noble"
            expected-tps: 9

    uses: ./.github/workflows/test-chat.yaml
    secrets: inherit
    with:
      snap-name: deepseek-r1
      snap-channel: ${{ inputs.snap-channel }}
      job-queue: ${{ matrix.jobs.job-queue }}
      provision-data: ${{ matrix.jobs.provision-data }}
      select-engine: ${{ matrix.jobs.select-engine }}
      install-nvidia-driver-version: ${{ matrix.jobs.install-nvidia-driver-version }}
      install-intel-npu-driver: ${{ matrix.jobs.install-intel-npu-driver == true }}
